---
mode: required
method: legacy
labels:
    step: "Installation type"
default: cinnamon
items:
    - id: cinnamon
      packages: [ cinnamon ]
      name: Cinnamon desktop
      description: "Install the supported graphical Cinnamon desktop. All required packages are included on this ISO."
      screenshot: "images/cinnamon.jpg"
    - id: ""
      packages: []
      name: "Basic system"
      description: "Install a basic system without a graphical desktop. All required packages are included on this ISO."
      screenshot: "images/nodesktop.jpg"
